# Generated by Django 3.1.2 on 2020-10-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(blank=True, default='', max_length=50)),
                ('FirstName', models.CharField(blank=True, default='', max_length=50)),
                ('LastName', models.CharField(blank=True, default='', max_length=50)),
                ('Phone', models.CharField(blank=True, default='', max_length=10)),
                ('Password', models.CharField(blank=True, default='', max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('SecurityQuestion', models.CharField(blank=True, default='', max_length=150)),
                ('SecurityAnswer', models.CharField(blank=True, default='', max_length=500)),
                ('profilePic', models.ImageField(default='media/user.png', upload_to='media')),
                ('Score', models.IntegerField(default=0)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
            ],
        ),
    ]
