# Generated by Django 3.1.2 on 2020-11-01 05:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('question', models.TextField()),
                ('totalVotes', models.IntegerField(blank=True, default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Views', models.IntegerField(default=0)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='App.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerId', models.CharField(default='', max_length=100, unique=True)),
                ('answer', models.TextField(blank=True)),
                ('totalVotes', models.IntegerField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('User', models.CharField(blank=True, default='', max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.questions')),
            ],
        ),
    ]
