# Generated by Django 3.1.3 on 2020-11-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_answers_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.CharField(blank=True, max_length=100)),
                ('userId', models.CharField(max_length=50)),
                ('voteType', models.IntegerField(blank=True)),
            ],
        ),
    ]
