# Generated by Django 3.1.6 on 2021-02-20 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_userdetail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
