# Generated by Django 3.1.6 on 2021-02-20 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_userdetail_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
