# Generated by Django 3.1.6 on 2021-02-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20210220_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
