# Generated by Django 3.1.6 on 2021-02-20 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20210220_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
