# Generated by Django 3.1.6 on 2021-02-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_userdetail_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='created_date',
        ),
    ]
